# Generated by Django 4.1.5 on 2023-01-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('infor', models.CharField(max_length=500)),
                ('publish', models.CharField(max_length=4)),
                ('updated', models.DateField(auto_now=True)),
                ('img', models.CharField(max_length=500)),
                ('des', models.CharField(max_length=200)),
            ],
        ),
    ]
